plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.moonleeeaf.forwardmyself'
    compileSdk 34
    
    defaultConfig {
        applicationId "io.github.moonleeeaf.forwardmyself"
        minSdk 16
        targetSdk 33
        versionCode 13000
        versionName "1.3.0"
        
        vectorDrawables { 
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding false
    }
}

dependencies {
    
}
